name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Cache OPAM dependencies
        id: cache-opam
        uses: actions/cache@v3
        with:
          path: ~/.opam
          key: opam-${{ runner.os }}-${{ hashFiles('**/opam') }}
          restore-keys: |
            opam-${{ runner.os }}-

      - name: Build Docker image
        run: docker build --cache-from proof-image  -t proof-image .

      - name: Run Docker container and build project
        run: docker run --rm proof-image

      - name: Run tests
        run: docker run --rm proof-image dune runtest